# Generated by Django 6.0.2 on 2026-02-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_arabic', models.CharField(blank=True, max_length=500, null=True)),
                ('brand_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upc', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('product_url', models.SlugField(max_length=500, unique=True)),
                ('main_image', models.URLField()),
                ('gallery_images', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_arabic', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='products_pr_title_7d8124_idx'), models.Index(fields=['brand_name'], name='products_pr_brand_n_3282c1_idx'), models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx')],
            },
        ),
    ]
