# Generated by Django 6.0.2 on 2026-02-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_name',
            new_name='BrandName',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='Descriptions',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_arabic',
            new_name='DescriptionsArabic',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='gallery_images',
            new_name='GalleryImages',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='main_image',
            new_name='Link',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_arabic',
            new_name='TitleArabic',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='upc',
            new_name='UPC',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='vat_price',
            new_name='VatPrice',
        ),
    ]
