# Generated by Django 6.0.2 on 2026-02-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_brand_name_product_brandname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='BrandName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Categories',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='TitleArabic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='UPC',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
