# Generated by Django 6.0.2 on 2026-02-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_brandname_alter_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
